name: inline-model-metrics

channels:
  - conda-forge

dependencies:
  - python=3.8
  - fortran-compiler
  - rsync
  - iris
  - netcdf4
  - numpy
  - pip:
    - metoffice-afterburner
    - tempest-helper
